name: Generate ASCII Portrait

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pillow

      - name: Generate portrait
        run: |
          python scripts/ascii.py

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update ASCII portrait
